### ISSUE TITLE
doesn't deal with multibyte unicode characters

### ISSUE THREAD

**Issue by azu** [groupon-testium/testium#124]
testium does not deal with multibyte unicode characters.

- Example for reproduction:  [azu/testium-multibyte-bug](https://github.com/azu/testium-multibyte-bug "azu/testium-multibyte-bug")
- Browser: phantomjs, chrome and firefox.

```js
// LICENSE : MIT
"use strict";
var assert = require("assert");
var injectBrowser = require('testium/mocha');
describe("multi byte char", function () {
    before(injectBrowser());
    beforeEach(function () {
        this.browser.navigateTo('https://www.google.com');
    });
    it('should type to textarea', function () {
        var multiByteText = "日本語 text";
        var input = this.browser.getElement('input[name="q"]');
        input.type(multiByteText);
        // garbled characters
        assert.equal(input.get("value"), multiByteText);
    });
});
```

Result: 

```
$ npm test

> testium-multibyte-bug@1.0.0 test /Users/azu/.ghq/github.com/azu/testium-multibyte-bug
> mocha test/



  multi byte char
    1) should type to textarea


  0 passing (2s)
  1 failing

  1) multi byte char should type to textarea:
     AssertionError: "�,� text" == "日本語 text"
[TESTIUM] Saved screenshot /Users/azu/.ghq/github.com/azu/testium-multibyte-bug/test/log/failed_screenshots/multi_byte_char_should_type_to_textarea4.png
      at Context.<anonymous> (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/test/test.js:14:16)
      at callFn (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:374:10)
      at /Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:299:14)
      at /Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:248:23)
      at /Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:271:7
      at done (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runnable.js:207:5)
      at callFn (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runnable.js:262:7)
      at Hook.Runnable.run (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:259:10)
      at Object._onImmediate (/Users/azu/.ghq/github.com/azu/testium-multibyte-bug/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:345:15)
```

failed_screenshots: 

![screen-shot](https://raw.githubusercontent.com/azu/testium-multibyte-bug/master/test/log/failed_screenshots/multi_byte_char_should_type_to_textarea3.png)

FYI: [request-sync](https://github.com/ForbesLindesay/request-sync "request-sync") is deprecated, use [sync-request](https://github.com/ForbesLindesay/sync-request)

**Comment by johan** [comment]
Interesting. I wonder if we might need a strategically placed `encodeURIComponent` somewhere, or even a [UTF8 encode/decode](http://ecmanaut.blogspot.se/2006/07/encoding-decoding-utf8-in-javascript.html) wrapper around the messaging to convey the right encoding to webdriver.

**Comment by EndangeredMassa** [comment]
Thanks for the report! We definitely want to fix this.
